### ISSUE TITLE
Cannot read properties of undefined (reading 'code')

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p-webrtc#125]
Running the browser-to-browser example  when using a VPN yields following error when connecting to ther other browsers address through the circuit relay. 

```
transport-manager.ts:126 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'code')
    at DefaultTransportManager.dial (transport-manager.ts:126:15)
    at async DialRequest.dialAction (index.ts:350:14)
    at async dial-request.ts:100:18
    at async Promise.any (:5173/index 0)
    at async DialRequest.run (dial-request.ts:85:14)
    at async DefaultDialer.createDialTarget (index.ts:210:26)
    at async DefaultDialer.dial (index.ts:173:12)
    at async DefaultConnectionManager.openConnection (index.ts:504:26)
    at async Libp2pNode.dial (libp2p.ts:369:12)
    at async window.connect.onclick (index.js:114:22)
```

The dial error is not thrown when I am not behind a VPN and the example works as expected. 

Expected behaviour (?). If establishing direct connection with WebRTC fails (because of the VPN), the example should still work nevertheless as I expected the relay would act as a TURN server, or there should be an error message of some sort.

**Comment by marcus-pousette** [comment]
https://github.com/libp2p/js-libp2p-webrtc/blob/2f8faa3ba6fe2dfd94fdab4664965c0a8be59e96/src/peer_transport/util.ts#L56

this is the issue, should be something like (?)

```typescript
promise.reject(errCode(new Error("failed to establish connection"), "ERR_FAILED_TO_ESTABLISH_CONNECTION"))
```
